

######### shapes 
shape_list = {
  'CMS_FF_closure_OSSS_mvis_mt_qcd_2017' : ['jetFakes'] ,
  'CMS_FF_closure_lpt_mt_qcd' : ['jetFakes'] ,
  'CMS_FF_closure_lpt_mt_tt' : ['jetFakes'] ,
  'CMS_FF_closure_lpt_mt_w' : ['jetFakes'] ,
  'CMS_FF_closure_lpt_xtrg_mt_qcd_2017' : ['jetFakes'] ,
  'CMS_FF_closure_lpt_xtrg_mt_tt_2017' : ['jetFakes'] ,
  'CMS_FF_closure_lpt_xtrg_mt_w_2017' : ['jetFakes'] ,
  'CMS_FF_closure_mt_mt_w_unc1_2017' : ['jetFakes'] ,
  'CMS_FF_closure_mt_mt_w_unc2_2017' : ['jetFakes'] ,
  'CMS_JER_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetAbsolute' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetAbsolute_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetBBEC1' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetBBEC1_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetEC2' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetEC2_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetFlavorQCD' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetHF' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetHF_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetRelativeBal' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_JetRelativeSample_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'TTL'] ,
  'CMS_ZLShape_mt_1prong1pizero_2017' : ['ZTTjet' ,'ZLLjet'] ,
  'CMS_ZLShape_mt_1prong_2017' : ['ZTTjet' ,'ZLLjet'] ,
  'CMS_eff_t_embedded_pt30to35_2017' : ['embedded'] ,
  'CMS_eff_t_embedded_pt35to40_2017' : ['embedded'] ,
  'CMS_eff_t_embedded_ptgt40_2017' : ['embedded'] ,
  'CMS_htt_boson_reso_met_1jet_2017' : ['ZTTjet' ,'ZLLjet'] ,
  'CMS_htt_boson_scale_met_1jet_2017' : ['ZTTjet' ,'ZLLjet'] ,
  'CMS_htt_dyShape' : ['ZTTjet' ,'ZLLjet'] ,
  'CMS_htt_emb_ttbar_2017' : ['embedded'] ,
  'CMS_htt_ttbarShape' : ['TTT', 'TT', 'TTL'] ,
  'CMS_mutautrg_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'STL', 'TTL'] ,
  'CMS_prefiring' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'STL', 'TTL'] ,
  'CMS_rawFF_mt_qcd_1jet_unc1_2017' : ['jetFakes'] ,
  'CMS_rawFF_mt_qcd_1jet_unc2_2017' : ['jetFakes'] ,
  'CMS_rawFF_mt_tt_unc1_2017' : ['jetFakes'] ,
  'CMS_rawFF_mt_tt_unc2_2017' : ['jetFakes'] ,
  'CMS_rawFF_mt_w_1jet_unc1_2017' : ['jetFakes'] ,
  'CMS_rawFF_mt_w_1jet_unc2_2017' : ['jetFakes'] ,
  'CMS_scale_m_eta1p2to2p1' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'STL', 'TTL'] ,
  'CMS_scale_m_eta2p1to2p4' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'STL', 'TTL'] ,
  'CMS_scale_m_etalt1p2' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'STL', 'TTL'] ,
  'CMS_scale_met_unclustered_2017' : ['VVT', 'STT', 'TTT', 'TT', 'VVL', 'STL', 'TTL'] ,
  'CMS_scale_t_1prong1pizero_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
  'CMS_scale_t_1prong_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
  'CMS_scale_t_3prong1pizero_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
  'CMS_scale_t_3prong_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
  'CMS_singlemutrg_2017' : ['VVT', 'STT', 'TTT', 'TT', 'ZTTjet' ,'ZLLjet', 'VVL', 'STL', 'TTL'] ,
  'CMS_tauideff_pt30to35_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
  'CMS_tauideff_pt35to40_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
  'CMS_tauideff_ptgt40_2017' : ['VVT', 'STT', 'TTT', 'TT'] ,
}

######### scale 
norm_list = {
    'CMS_eff_m_2017' : [1.02, ['VVT', 1.02, 'STT', 1.02, 'TTT', 'TT', 1.02, 'ZTTjet' ,'ZLLjet', 1.02, 'VVL', 1.02, 'STL', 1.02, 'TTL', 1.01, 'embedded']] ,
    'CMS_eff_m_embedded_2017' : [1.01732, ['embedded']] ,
    'CMS_eff_t_againstemu_mt_2017' : [1.01, ['VVT', 1.01, 'STT', 1.01, 'TTT', 'TT']] ,
    'CMS_htt_doublemutrg_2017' : [1.04, ['embedded']] ,
    'CMS_htt_eff_b_2017' : [1.005, ['VVT', 1.005, 'ZTTjet' ,'ZLLjet', 1.005, 'VVL']] ,
    'CMS_htt_eff_b_TT_2017' : [1.05, ['STT', 1.05, 'TTT', 'TT', 1.05, 'STL', 1.05, 'TTL']] ,
    'CMS_htt_stXsec' : [1.05, ['STT', 1.05, 'STL']] ,
    'CMS_htt_tjXsec' : [1.042, ['TTT', 'TT', 1.042, 'TTL']] ,
    'CMS_htt_vvXsec' : [1.05, ['VVT', 1.05, 'VVL']] ,
    'CMS_htt_zjXsec' : [1.02, ['ZTTjet' ,'ZLLjet']],
    'CMS_mFakeTau_2017' : [1.2, ['ZTTjet' ,'ZLLjet', 1.2, 'VVL', 1.2, 'STL', 1.2, 'TTL']] ,
    'lumi_Run2017' : [1.02, ['VVT', 1.02, 'STT', 1.02, 'TTT', 'TT', 1.02, 'ZTTjet' ,'ZLLjet', 1.02, 'VVL', 1.02, 'STL', 1.02, 'TTL']] ,
    'lumi_XYfactorization' : [1.008, ['VVT', 1.008, 'STT', 1.008, 'TTT', 'TT', 1.008, 'ZTTjet' ,'ZLLjet', 1.008, 'VVL', 1.008, 'STL', 1.008, 'TTL']] ,
    'lumi_beamBeamDeflection' : [1.004, ['VVT', 1.004, 'STT', 1.004, 'TTT', 'TT', 1.004, 'ZTTjet' ,'ZLLjet', 1.004, 'VVL', 1.004, 'STL', 1.004, 'TTL']] ,
    'lumi_beamCurrentCalibration' : [1.003, ['VVT', 1.003, 'STT', 1.003, 'TTT', 'TT', 1.003, 'ZTTjet' ,'ZLLjet', 1.003, 'VVL', 1.003, 'STL', 1.003, 'TTL']] ,
    'lumi_dynamicBeta' : [1.005, ['VVT', 1.005, 'STT', 1.005, 'TTT', 'TT', 1.005, 'ZTTjet' ,'ZLLjet', 1.005, 'VVL', 1.005, 'STL', 1.005, 'TTL']] ,
    'lumi_ghostsAndSatellites' : [1.001, ['VVT', 1.001, 'STT', 1.001, 'TTT', 'TT', 1.001, 'ZTTjet' ,'ZLLjet', 1.001, 'VVL', 1.001, 'STL', 1.001, 'TTL']] ,
    'lumi_lengthScale' : [1.003, ['VVT', 1.003, 'STT', 1.003, 'TTT', 'TT', 1.003, 'ZTTjet' ,'ZLLjet', 1.003, 'VVL', 1.003, 'STL', 1.003, 'TTL']] ,
}
