du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraB_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_02_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_03_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_03_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_03_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_03_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_03_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_11_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_11_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_11_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_11_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_11_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraC_11_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraD_01_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_01_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraE_02_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_01_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_02_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/MET_EraF_03_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraB_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_02_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_03_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_03_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_03_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_03_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_03_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_11_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_11_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_11_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_11_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_11_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraC_11_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraD_01_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_00_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_01_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraE_02_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_01_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_02_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_03_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_03_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_03_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_03_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_03_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/hadd/blinded_MET_EraF_03_05.root 
