du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY1JetsToLL_M-50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY1JetsToLL_M-50_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY1JetsToLL_M-50_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY1JetsToLL_M-50_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY1JetsToLL_M-50_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY2JetsToLL_M-50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY2JetsToLL_M-50_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY3JetsToLL_M-50_TuneCP5_ext1_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY3JetsToLL_M-50_TuneCP5_v1_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DY4JetsToLL_M-50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-10to50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-10to50_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-10to50_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-10to50_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-10to50_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_03_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_03_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_04_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_04_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_05_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_05_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_06_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_07_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_08_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_ext1_v1_09_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_01_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_02_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_02_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_03_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_03_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_04_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_04_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_05_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_06_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_07_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_08_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/DYJetsToLL_M-50_TuneCP5_v1_09_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/EWKWMinus2Jets_WToLNu_M-50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/EWKWPlus2Jets_WToLNu_M-50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/EWKZ2Jets_ZToLL_M-50_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/EWKZ2Jets_ZToNuNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/GluGluHToTauTau_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/GluGluHToWWTo2L2Nu_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0000_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraB_0001_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0000_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0001_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0001_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0001_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0001_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0001_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0001_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0002_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0003_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0003_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0003_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0003_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0003_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0011_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0011_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0011_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0011_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0011_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraC_0011_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0000_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraD_0001_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0000_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0001_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraE_0002_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0000_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0001_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_010.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0002_09.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/MET_EraF_0003_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_t-channel_top_4f_inclusiveDecays_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_t-channel_top_4f_inclusiveDecays_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_tW_top_5f_inclusiveDecays_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ST_tW_top_5f_inclusiveDecays_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTTo2L2Nu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTTo2L2Nu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToHadronic_TuneCP5_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/TTToSemiLeptonic_TuneCP5_00_08.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/VBFHToTauTau_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/VBFHToWWTo2L2Nu_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/VVTo2L2Nu_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/VVTo2L2Nu_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/VVTo2L2Nu_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W1JetsToLNu_TuneCP5_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W2JetsToLNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W2JetsToLNu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W3JetsToLNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W3JetsToLNu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W3JetsToLNu_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W4JetsToLNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/W4JetsToLNu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Incl_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Incl_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Incl_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Incl_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Incl_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Incl_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_Inclv2_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_06.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WJetsToLNu_TuneCP5_00_07.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WWTo1L1Nu2Q_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WWToLNuQQ_NNPDF31_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WWToLNuQQ_NNPDF31_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WWW_4F_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WWZ_4F_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WW_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WZTo3LNu_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WZTo3LNu_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WZZ_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WZ_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WminusHToTauTau_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/WplusHToTauTau_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZHToTauTau_M125_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-100To200_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-100To200_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-100To200_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-1200To2500_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-200To400_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-200To400_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-200To400_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-2500ToInf_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-400To600_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-400To600_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-600To800_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZJetsToNuNu_HT-800To1200_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo2L2Q_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo2L2Q_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo2L2Q_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo2L2Q_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo2L2Q_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo4L_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo4L_TuneCP5_00_01.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo4L_TuneCP5_00_02.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo4L_TuneCP5_00_03.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo4L_TuneCP5_00_04.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZTo4L_TuneCP5_00_05.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZZ_TuneCP5_00_00.root 
du -sh /hdfs/store/user/jmadhusu/with_boostedtau/2017_skimmed/with_boostedtaus/etau_hadd/ZZ_TuneCP5_00_00.root 
