hadd zprime_combined/Signal_Zpbaryonic2018_1.root zprime/Zpbaryonic_*_1.root 
hadd zprime_combined/Signal_Zpbaryonic2018_2.root zprime/Zpbaryonic_*_2.root 
hadd zprime_combined/Signal_Zpbaryonic2018_3.root zprime/Zpbaryonic_*_3.root 
hadd zprime_combined/Signal_Zpbaryonic2018_4.root zprime/Zpbaryonic_*_4.root 
hadd zprime_combined/Signal_Zpbaryonic2018_5.root zprime/Zpbaryonic_*_5.root 
hadd zprime_combined/Signal_Zpbaryonic2018_6.root zprime/Zpbaryonic_*_6.root 
hadd zprime_combined/Signal_Zpbaryonic2018_7.root zprime/Zpbaryonic_*_7.root 
hadd zprime_combined/Signal_Zpbaryonic2018_8.root zprime/Zpbaryonic_*_8.root 
hadd zprime_combined/Signal_Zpbaryonic2018_9.root zprime/Zpbaryonic_*_9.root 
hadd zprime_combined/Signal_Zpbaryonic2018_10.root zprime/Zpbaryonic_*_10.root 
hadd zprime_combined/Signal_Zpbaryonic2018_11.root zprime/Zpbaryonic_*_11.root 
hadd zprime_combined/Signal_Zpbaryonic2018_12.root zprime/Zpbaryonic_*_12.root 
hadd zprime_combined/Signal_Zpbaryonic2018_13.root zprime/Zpbaryonic_*_13.root 
hadd zprime_combined/Signal_Zpbaryonic2018_14.root zprime/Zpbaryonic_*_14.root 
hadd zprime_combined/Signal_Zpbaryonic2018_15.root zprime/Zpbaryonic_*_15.root 
hadd zprime_combined/Signal_Zpbaryonic2018_16.root zprime/Zpbaryonic_*_16.root 
hadd zprime_combined/Signal_Zpbaryonic2018_17.root zprime/Zpbaryonic_*_17.root 
hadd zprime_combined/Signal_Zpbaryonic2018_18.root zprime/Zpbaryonic_*_18.root 
hadd zprime_combined/Signal_Zpbaryonic2018_19.root zprime/Zpbaryonic_*_19.root 
hadd zprime_combined/Signal_Zpbaryonic2018_20.root zprime/Zpbaryonic_*_20.root 
hadd zprime_combined/Signal_Zpbaryonic2018_21.root zprime/Zpbaryonic_*_21.root 
hadd zprime_combined/Signal_Zpbaryonic2018_22.root zprime/Zpbaryonic_*_22.root 
hadd zprime_combined/Signal_Zpbaryonic2018_23.root zprime/Zpbaryonic_*_23.root 
hadd zprime_combined/Signal_Zpbaryonic2018_24.root zprime/Zpbaryonic_*_24.root 
hadd zprime_combined/Signal_Zpbaryonic2018_25.root zprime/Zpbaryonic_*_25.root 
hadd zprime_combined/Signal_Zpbaryonic2018_26.root zprime/Zpbaryonic_*_26.root 
hadd zprime_combined/Signal_Zpbaryonic2018_27.root zprime/Zpbaryonic_*_27.root 
hadd zprime_combined/Signal_Zpbaryonic2018_28.root zprime/Zpbaryonic_*_28.root 
hadd zprime_combined/Signal_Zpbaryonic2018_29.root zprime/Zpbaryonic_*_29.root 
hadd zprime_combined/Signal_Zpbaryonic2018_30.root zprime/Zpbaryonic_*_30.root 
hadd zprime_combined/Signal_Zpbaryonic2018_31.root zprime/Zpbaryonic_*_31.root 
hadd zprime_combined/Signal_Zpbaryonic2018_32.root zprime/Zpbaryonic_*_32.root 
hadd zprime_combined/Signal_Zpbaryonic2018_33.root zprime/Zpbaryonic_*_33.root 
hadd zprime_combined/Signal_Zpbaryonic2018_34.root zprime/Zpbaryonic_*_34.root 
hadd zprime_combined/Signal_Zpbaryonic2018_35.root zprime/Zpbaryonic_*_35.root 
hadd zprime_combined/Signal_Zpbaryonic2018_36.root zprime/Zpbaryonic_*_36.root 
hadd zprime_combined/Signal_Zpbaryonic2018_37.root zprime/Zpbaryonic_*_37.root 
hadd zprime_combined/Signal_Zpbaryonic2018_38.root zprime/Zpbaryonic_*_38.root 
hadd zprime_combined/Signal_Zpbaryonic2018_39.root zprime/Zpbaryonic_*_39.root 
hadd zprime_combined/Signal_Zpbaryonic2018_40.root zprime/Zpbaryonic_*_40.root 
hadd zprime_combined/Signal_Zpbaryonic2018_41.root zprime/Zpbaryonic_*_41.root 
hadd zprime_combined/Signal_Zpbaryonic2018_42.root zprime/Zpbaryonic_*_42.root 
hadd zprime_combined/Signal_Zpbaryonic2018_43.root zprime/Zpbaryonic_*_43.root 
